### ISSUE TITLE
Failing because of missing `make` and `gcc`

### ISSUE THREAD

**Issue by mputilin** [geerlingguy/ansible-role-daemonize#4]
Please, add something like

```
- name: Install dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
   - gcc
   - make
```

**Comment by geerlingguy** [comment]
@mputilin - The requirements state the that the necessary build tools should be present before running this role (see https://github.com/geerlingguy/ansible-role-daemonize#requirements); I think that's sufficient, and don't want to hardcode this task in this role as that precedent would require I add it to many other roles, and they'd all be doing the same thing.

It might be more efficient to just have a 'build tools' role that does it cross-platform and have a soft dependency on that.

**Comment by geerlingguy** [comment]
Quickest way to do this in a playbook:

``` yaml
  pre_tasks:
    - name: Ensure build dependencies are installed (RedHat).
      yum: name="@Development tools" state=present
      when: ansible_os_family == 'RedHat'

    - name: Ensure build dependencies are installed (Debian).
      apt: name=build-essential state=installed
      when: ansible_os_family == 'Debian'
```
